version: '3'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: ecommerce_db

  db:
    image: mysql:5.7
    ports:                   
      - "3306:3306"          
    volumes:
      - db_data:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecommerce_db

volumes:
  db_data:
